--13. It is thought that since left-handed pitchers are more rare, causing batters to face 
--    them less often, that they are more effective. Investigate this claim and present 
--    evidence to either support or dispute this claim. First, determine just how rare left-handed 
--    pitchers are compared with right-handed pitchers. Are left-handed pitchers more likely to win 
--    the Cy Young Award? Are they more likely to make it into the hall of fame?